using System.Globalization;
using System.Text;
using SacredStudio.Model;

namespace SacredStudio.CodeGen;

/// <summary>
/// Turns an EditorProject into a runtime Lua module that drives the proven
/// SacredSDK runtime story API (npcobj + sacred.*). The generated file is meant
/// to live at custom/lua/&lt;ModName&gt;/init.lua. The DLL executes every .lua
/// under custom/lua/** once at load — there is no external hook that calls
/// M.apply(); the module arms itself (sacred.on_world_load + on_tick with the
/// 2-tick settle from examples/15_storyline.lua) and replays M.apply() once
/// the hero is live after each world load. M.apply stays exported for manual
/// re-runs from the console.
///
/// Nothing here patches FunkCode/.bin — every construct is a runtime replay, in
/// line with docs/24-storyline.md ("everything is runtime, never a .bin edit").
/// </summary>
public static class LuaEmitter
{
    public static string Emit(EditorProject p)
    {
        var sb = new StringBuilder();
        var ci = CultureInfo.InvariantCulture;

        sb.AppendLine($"-- Generated by SacredStudio. Mod: {p.ModName}");
        if (!string.IsNullOrWhiteSpace(p.Description))
            foreach (var line in p.Description.Replace("\r", "").Split('\n'))
                sb.AppendLine($"-- {line}");
        if (!string.IsNullOrWhiteSpace(p.TargetClass))
            sb.AppendLine($"-- Target class: {p.TargetClass}");
        sb.AppendLine("--");
        sb.AppendLine("-- Runtime-only: spawns/markers replay through the engine; no .bin is touched.");
        sb.AppendLine("-- The DLL runtime hook is expected to require this module and call M.apply().");
        sb.AppendLine();
        sb.AppendLine("local N = require \"npcobj\"");
        sb.AppendLine();
        sb.AppendLine("local M = {}");
        sb.AppendLine();

        EmitPoints(sb, p);
        EmitZones(sb, p);

        sb.AppendLine("function M.apply()");
        EmitNpcs(sb, p, ci);
        EmitItems(sb, p);
        sb.AppendLine("end");
        sb.AppendLine();
        sb.AppendLine("return M");

        return sb.ToString();
    }

    private static void EmitPoints(StringBuilder sb, EditorProject p)
    {
        var points = p.Points.ToList();
        if (points.Count == 0) return;
        sb.AppendLine("-- Named positions (world tiles)");
        foreach (var pt in points)
            sb.AppendLine($"M.{pt.LuaLocal} = {{ {pt.Pos.Wx}, {pt.Pos.Wy} }}  -- {Escape(pt.Name)}");
        sb.AppendLine();
    }

    private static void EmitZones(StringBuilder sb, EditorProject p)
    {
        var zones = p.Zones.ToList();
        if (zones.Count == 0) return;
        sb.AppendLine("-- Axis-aligned world-tile zones (inclusive bounds)");
        foreach (var z in zones)
            sb.AppendLine(
                $"M.{z.LuaLocal} = {{ x0 = {z.Pos.Wx}, y0 = {z.Pos.Wy}, " +
                $"x1 = {z.MaxWx}, y1 = {z.MaxWy} }}  -- {Escape(z.Name)}");
        sb.AppendLine();
        sb.AppendLine("-- Test whether a world tile (wx, wy) is inside a zone table.");
        sb.AppendLine("function M.in_zone(z, wx, wy)");
        sb.AppendLine("    return wx >= z.x0 and wx <= z.x1 and wy >= z.y0 and wy <= z.y1");
        sb.AppendLine("end");
        sb.AppendLine();
    }

    private static void EmitNpcs(StringBuilder sb, EditorProject p, CultureInfo ci)
    {
        var npcs = p.Npcs.ToList();
        if (npcs.Count == 0) return;
        sb.AppendLine("    -- NPCs (engine CreateNPC via dev template + surgical deltas)");
        foreach (var n in npcs)
        {
            string local = n.LuaLocal;
            var opts = new List<string> { $"sub_id = {n.SubId}" };
            if (n.NpcType != 0)
            {
                string typeExpr = n.NpcTypeName is { Length: > 0 } tn ? $"NPC.{tn}" : n.NpcType.ToString(ci);
                opts.Insert(0, $"type = {typeExpr}");
            }
            opts.Add("pos = \"CPOS:HERO\"");

            sb.AppendLine($"    local {local} = N.spawn_template(" +
                          $"\"{NpcArchetypeNames.ToLua(n.Archetype)}\", {{ {string.Join(", ", opts)} }})");
            // Engine move to the authored post (no struct writes).
            sb.AppendLine($"    {local}:teleport({n.Pos.Wx}, {n.Pos.Wy})");
            if (n.StanceClass is int sc && n.StanceMatrix is int sm)
                sb.AppendLine($"    {local}:stance({sc}, {sm})");
            if (n.Level is int lvl)
                sb.AppendLine($"    {local}:level({lvl})");
            if (n.Stationary)
                sb.AppendLine($"    {local}:stationary(true)");
            if (n.Immortal)
                sb.AppendLine($"    {local}:invuln(true)");
            foreach (var e in n.Equipment)
            {
                string itemExpr = e.ItemTypeName is { Length: > 0 } itn ? $"ITEM.{itn}" : e.ItemType.ToString(ci);
                sb.AppendLine($"    {local}:equip({itemExpr}, 0x{e.Slot:X2})");
            }
            if (n.QuestGiver)
            {
                string nameArg = string.IsNullOrWhiteSpace(n.Name) ? "\"\"" : $"\"{Escape(n.Name)}\"";
                sb.AppendLine(n.Level is int qlvl
                    ? $"    {local}:make_quest_giver({nameArg}, {qlvl})"
                    : $"    {local}:make_quest_giver({nameArg})");
            }
            else if (!string.IsNullOrWhiteSpace(n.Name))
            {
                sb.AppendLine($"    {local}:set_name(\"{Escape(n.Name)}\")");
            }
            sb.AppendLine();
        }
    }

    private static void EmitItems(StringBuilder sb, EditorProject p)
    {
        var items = p.Items.ToList();
        if (items.Count == 0) return;
        sb.AppendLine("    -- World item drops");
        foreach (var it in items)
        {
            string typeExpr = it.ItemTypeName is { Length: > 0 } tn ? $"ITEM.{tn}" : it.ItemType.ToString(CultureInfo.InvariantCulture);
            string comment = string.IsNullOrWhiteSpace(it.Name) ? "" : $"  -- {Escape(it.Name)}";
            sb.AppendLine($"    sacred.spawn_item({typeExpr}, {it.Pos.Wx}, {it.Pos.Wy}){comment}");
        }
        sb.AppendLine();
    }

    private static string Escape(string s) =>
        s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "");
}
