"""Bulk-dump ALL quests' scripts to one big Markdown file. Counterpart of
quest_book.py (which dumps quest TEXTS); this dumps the FunkCode bytecode
records each quest is composed of, with subsystem labels.

Defaults are the historical ones (base campaign, 8 per-class dirs,
sdk/logs/quest_scripts.md).  For per-quest files — which is what later
analysis passes should read — use quest_shards.py instead; this book stays
for continuity.

    python quest_script_book.py                     # legacy output
    python quest_script_book.py --sources all --out sdk/logs/quest_scripts_all.md
"""
import os, sys, io, argparse, contextlib
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import funkcode_sources as fs
import quest_dump as qd
import quest_script as qs
try: sys.stdout.reconfigure(encoding="utf-8")
except Exception: pass

OUT = os.path.join(fs.GAME_ROOT, "sdk", "logs", "quest_scripts.md")
SOURCES = "base-classes"


def capture(prefix, max_per_class=20):
    buf = io.StringIO()
    with contextlib.redirect_stdout(buf):
        qs.dump_quest_script(prefix, sources=SOURCES, max_per_class=max_per_class)
    return buf.getvalue()


def dq_numeric_prefixes():
    toks = qd.all_tokens()
    out = set()
    for t in toks:
        if t.startswith("DQ_") and "_" in t[3:]:
            head = t.split("_", 2)
            if len(head) >= 2 and head[1].isdigit():
                out.add(f"DQ_{head[1]}")
    return sorted(out, key=lambda s: int(s[3:]))


def main(out=OUT):
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        f.write("# Sacred Gold — Quest scripts (FunkCode dump)\n\n")
        f.write("Auto-generated by `sdk/tools/quest_script_book.py`. Each section is\n"
                "the FunkCode records (with tag-labelled subsystem dispatch) that\n"
                "implement one quest.\n\n")

        hq = qd.list_prefixes("HQ"); print(f"HQ: {len(hq)}")
        f.write(f"## Main quests (HQ): {len(hq)}\n\n")
        for p in hq:
            f.write(f"### {p}\n\n```\n{capture(p, 12)}\n```\n\n")

        nq = qd.list_prefixes("NQ"); print(f"NQ: {len(nq)}")
        f.write(f"## Named quests (NQ): {len(nq)}\n\n")
        for p in nq:
            f.write(f"### {p}\n\n```\n{capture(p, 12)}\n```\n\n")

        rb = qd.list_prefixes("RB"); print(f"RB: {len(rb)}")
        f.write(f"## Runebook quests (RB): {len(rb)}\n\n")
        for p in rb:
            f.write(f"### {p}\n\n```\n{capture(p, 12)}\n```\n\n")

        dqn = dq_numeric_prefixes(); print(f"DQ: {len(dqn)}")
        f.write(f"## Daily-quest instances (DQ_<id>): {len(dqn)}\n\n")
        for p in dqn:
            f.write(f"### {p}\n\n```\n{capture(p, 6)}\n```\n\n")

    print(f"\nwrote {out}")
    print(f"size: {os.path.getsize(out):,} bytes")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--sources", default=SOURCES,
                    help="source spec (default: base-classes = legacy behaviour)")
    ap.add_argument("--out", default=OUT)
    args = ap.parse_args()
    SOURCES = args.sources
    qd.DEFAULT_SOURCES = args.sources
    main(args.out)
