"""Dump every quest's text card to a single Markdown 'questbook' file.

Iterates HQ_* main quests, NQ_* named quests, RB_* runebook and DQ_<N>
daily-quest instances. Reuses quest_dump.py's resolution machinery.

Defaults are the historical ones (base campaign, 8 per-class dirs,
sdk/logs/questbook.md) — pass --sources to widen the corpus:

    python quest_book.py                       # legacy output, unchanged
    python quest_book.py --sources all --out sdk/logs/questbook_all.md
"""
import os, sys, io, argparse, contextlib
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import funkcode_sources as fs
import quest_dump as qd
try: sys.stdout.reconfigure(encoding="utf-8")
except Exception: pass

OUT = os.path.join(fs.GAME_ROOT, "sdk", "logs", "questbook.md")


def capture(prefix):
    buf = io.StringIO()
    with contextlib.redirect_stdout(buf):
        qd.dump_card(prefix)
    return buf.getvalue()


def dq_numeric_prefixes():
    """Every DQ_<NNNN> seen in FunkCode (numeric daily-quest instances)."""
    toks = qd.all_tokens()
    out = set()
    for t in toks:
        if t.startswith("DQ_") and "_" in t[3:]:
            head = t.split("_", 2)
            if len(head) >= 2 and head[1].isdigit():
                out.add(f"DQ_{head[1]}")
    return sorted(out, key=lambda s: int(s[3:]))


def main(out=OUT):
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        f.write("# Sacred Gold — Quest book\n\n")
        f.write("Auto-generated by `sdk/tools/quest_book.py`. "
                "Each section is one quest's resolved text content.\n\n")

        hq = qd.list_prefixes("HQ")
        f.write(f"## Main quests (HQ): {len(hq)}\n\n")
        print(f"dumping {len(hq)} HQ quests...")
        for p in hq:
            f.write(f"### {p}\n\n```\n{capture(p)}\n```\n\n")

        nq = qd.list_prefixes("NQ")
        f.write(f"## Named quests (NQ): {len(nq)}\n\n")
        print(f"dumping {len(nq)} NQ quests...")
        for p in nq:
            f.write(f"### {p}\n\n```\n{capture(p)}\n```\n\n")

        rb = qd.list_prefixes("RB")
        f.write(f"## Runebook quests (RB): {len(rb)}\n\n")
        print(f"dumping {len(rb)} RB quests...")
        for p in rb:
            f.write(f"### {p}\n\n```\n{capture(p)}\n```\n\n")

        dqn = dq_numeric_prefixes()
        f.write(f"## Daily-quest instances (DQ_<id>): {len(dqn)}\n\n")
        print(f"dumping {len(dqn)} DQ_<n> quests...")
        for p in dqn:
            f.write(f"### {p}\n\n```\n{capture(p)}\n```\n\n")

    print(f"\nwrote {out}")
    print(f"size: {os.path.getsize(out):,} bytes")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--sources", default=qd.DEFAULT_SOURCES,
                    help="source spec (default: base-classes = legacy behaviour)")
    ap.add_argument("--out", default=OUT)
    args = ap.parse_args()
    qd.DEFAULT_SOURCES = args.sources
    main(args.out)
