"""Bulk-dump ALL quests' scripts to one big Markdown file. Counterpart of
quest_book.py (which dumps quest TEXTS); this dumps the FunkCode bytecode
records each quest is composed of, with subsystem labels."""
import os, sys, io, contextlib
sys.path.insert(0, os.path.dirname(__file__))
import quest_dump as qd
import quest_script as qs
try: sys.stdout.reconfigure(encoding="utf-8")
except Exception: pass

OUT = r"E:\SteamLibrary\steamapps\common\Sacred Gold\sdk\logs\quest_scripts.md"
os.makedirs(os.path.dirname(OUT), exist_ok=True)

def capture(prefix, max_per_class=20):
    buf = io.StringIO()
    with contextlib.redirect_stdout(buf):
        qs.dump_quest_script(prefix, qs.ALL_CLASSES, max_per_class=max_per_class)
    return buf.getvalue()

def dq_numeric_prefixes():
    toks = qd.all_tokens()
    out = set()
    for t in toks:
        if t.startswith("DQ_") and "_" in t[3:]:
            head = t.split("_", 2)
            if len(head) >= 2 and head[1].isdigit():
                out.add(f"DQ_{head[1]}")
    return sorted(out, key=lambda s: int(s[3:]))

with open(OUT, "w", encoding="utf-8") as f:
    f.write("# Sacred Gold — Quest scripts (FunkCode dump)\n\n")
    f.write("Auto-generated by `sdk/tools/quest_script_book.py`. Each section is\n"
            "the FunkCode records (with tag-labelled subsystem dispatch) that\n"
            "implement one quest.\n\n")

    hq = qd.list_prefixes("HQ"); print(f"HQ: {len(hq)}")
    f.write(f"## Main quests (HQ): {len(hq)}\n\n")
    for p in hq:
        f.write(f"### {p}\n\n```\n{capture(p, 12)}\n```\n\n")

    nq = qd.list_prefixes("NQ"); print(f"NQ: {len(nq)}")
    f.write(f"## Named quests (NQ): {len(nq)}\n\n")
    for p in nq:
        f.write(f"### {p}\n\n```\n{capture(p, 12)}\n```\n\n")

    rb = qd.list_prefixes("RB"); print(f"RB: {len(rb)}")
    f.write(f"## Runebook quests (RB): {len(rb)}\n\n")
    for p in rb:
        f.write(f"### {p}\n\n```\n{capture(p, 12)}\n```\n\n")

    dqn = dq_numeric_prefixes(); print(f"DQ: {len(dqn)}")
    f.write(f"## Daily-quest instances (DQ_<id>): {len(dqn)}\n\n")
    for p in dqn:
        f.write(f"### {p}\n\n```\n{capture(p, 6)}\n```\n\n")

print(f"\nwrote {OUT}")
print(f"size: {os.path.getsize(OUT):,} bytes")
