"""Dump every quest's text card to a single Markdown 'questbook' file.

Iterates HQ_* main quests, NQ_* named quests and (optionally) DQ_<N>_* daily
quest instances. Reuses quest_dump.py's resolution machinery.
"""
import os, sys, io, contextlib
sys.path.insert(0, os.path.dirname(__file__))
import quest_dump as qd
try: sys.stdout.reconfigure(encoding="utf-8")
except Exception: pass

OUT = r"E:\SteamLibrary\steamapps\common\Sacred Gold\sdk\logs\questbook.md"
os.makedirs(os.path.dirname(OUT), exist_ok=True)

def capture(prefix):
    buf = io.StringIO()
    with contextlib.redirect_stdout(buf):
        qd.dump_card(prefix)
    return buf.getvalue()

def dq_numeric_prefixes():
    """Every DQ_<NNNN> seen in FunkCode (numeric daily-quest instances)."""
    toks = qd.all_tokens()
    out = set()
    for t in toks:
        if t.startswith("DQ_") and "_" in t[3:]:
            head = t.split("_", 2)
            if len(head) >= 2 and head[1].isdigit():
                out.add(f"DQ_{head[1]}")
    return sorted(out, key=lambda s: int(s[3:]))

with open(OUT, "w", encoding="utf-8") as f:
    f.write("# Sacred Gold — Quest book\n\n")
    f.write("Auto-generated by `sdk/tools/quest_book.py`. "
            "Each section is one quest's resolved text content.\n\n")

    # ---- HQ_* (main story) ----
    hq = qd.list_prefixes("HQ")
    f.write(f"## Main quests (HQ): {len(hq)}\n\n")
    print(f"dumping {len(hq)} HQ quests...")
    for p in hq:
        f.write(f"### {p}\n\n```\n")
        f.write(capture(p))
        f.write("\n```\n\n")

    # ---- NQ_* (named) ----
    nq = qd.list_prefixes("NQ")
    f.write(f"## Named quests (NQ): {len(nq)}\n\n")
    print(f"dumping {len(nq)} NQ quests...")
    for p in nq:
        f.write(f"### {p}\n\n```\n")
        f.write(capture(p))
        f.write("\n```\n\n")

    # ---- RB_* (runebook) ----
    rb = qd.list_prefixes("RB")
    f.write(f"## Runebook quests (RB): {len(rb)}\n\n")
    print(f"dumping {len(rb)} RB quests...")
    for p in rb:
        f.write(f"### {p}\n\n```\n")
        f.write(capture(p))
        f.write("\n```\n\n")

    # ---- DQ_<n>_* (daily-quest instances) ----
    dqn = dq_numeric_prefixes()
    f.write(f"## Daily-quest instances (DQ_<id>): {len(dqn)}\n\n")
    print(f"dumping {len(dqn)} DQ_<n> quests...")
    for p in dqn:
        f.write(f"### {p}\n\n```\n")
        f.write(capture(p))
        f.write("\n```\n\n")

print(f"\nwrote {OUT}")
sz = os.path.getsize(OUT)
print(f"size: {sz:,} bytes")
